language: node_js
node_js:
  - "10"
cache:
  directories:
  - node_modules
deploy:
  provider: surge
  project: ./public
  skip_cleanup: true
  domain: elegant.surge.sh
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
after_success:
  - "npm run deploy"
